### ISSUE TITLE
Web Parser getPageTitle normalize error

### ISSUE THREAD

**Issue by cjdhein** [cjdhein/perseus#5]
`Traceback (most recent call last):
  File "core.py", line 23, in <module>
    testTree.beginCrawl()
  File "/home/cjdhein/perseus/crawler/pagetree.py", line 38, in beginCrawl
    wc.crawl(aNode)
  File "/home/cjdhein/perseus/crawler/webcrawler.py", line 43, in crawl
    page.setTitle(self.parser.getPageTitle(theSoup))
  File "/home/cjdhein/perseus/crawler/pagenode.py", line 23, in setTitle
    scrubbed = unicodedata.normalize('NFKD', title).encode('ascii','ignore')
TypeError: normalize() argument 2 must be unicode, not None`

**Comment by cjdhein** [comment]
Fixed after changing to requests.
